Issue#9: COrrect linting errors

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,10 @@
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
 echo '🏗️👷 Verifying code formatting, types and building project before committing'
 
 # Check Prettier standards
-npm run check-format ||
+npm run check:format ||
 (
     echo '❌🤡 Prettier Check Failed. Run npm run format, add changes and try commit again. 🤡❌';
     false;
@@ -10,12 +13,12 @@ npm run check-format ||
 # Check ESLint Standards
 npm run lint ||
 (
-        echo '❌😤 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again. 😤❌'
+        echo '❌😤 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again. 😤❌';
         false; 
 )
 
 # Check tsconfig standards
-npm run check-types ||
+npm run check:types ||
 (
     echo '🤡😂❌🤡 Failed Type check. Make the required changes listed above, add changes and try to commit again. 🤡❌😂🤡'
     false;
@@ -31,4 +34,4 @@ npm run build ||
 )
 
 # If everything passes... Now we can commit
-echo '✅✅✅✅ Committing chnages ✅✅✅✅'
+echo '✅✅✅✅ Committing changes ✅✅✅✅'
